services:
  audiobookshelf:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "5000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    command: ["node", "build/index.js", "--transport=streamable-http"]