name: Release Docker image and create GitHub Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image and save as tar
        run: |
          IMAGE_NAME="audiobookshelf-mcp:${{ github.run_id }}"
          echo "Building image ${IMAGE_NAME}"
          docker build -t "$IMAGE_NAME" .
          mkdir -p release-assets
          docker save "$IMAGE_NAME" -o release-assets/audiobookshelf-mcp-${{ github.run_id }}.tar

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            Automated release for commit ${{ github.sha }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Docker tar to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release-assets/audiobookshelf-mcp-${{ github.run_id }}.tar
          asset_name: audiobookshelf-mcp-${{ github.run_id }}.tar
          asset_content_type: application/x-tar